//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Assets
{
    [Serializable]
    public class ClockMsg : Message
    {
        public const string k_RosMessageName = "Assets/Clock";
        public override string RosMessageName => k_RosMessageName;

        //  This message communicates the current time.
        // 
        //  For more information, see https://design.ros2.org/articles/clock_and_time.html.
        public BuiltinInterfaces.TimeMsg clock;

        public ClockMsg()
        {
            this.clock = new BuiltinInterfaces.TimeMsg();
        }

        public ClockMsg(BuiltinInterfaces.TimeMsg clock)
        {
            this.clock = clock;
        }

        public static ClockMsg Deserialize(MessageDeserializer deserializer) => new ClockMsg(deserializer);

        private ClockMsg(MessageDeserializer deserializer)
        {
            this.clock = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.clock);
        }

        public override string ToString()
        {
            return "ClockMsg: " +
            "\nclock: " + clock.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
